# Generated by Django 3.1.7 on 2021-03-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votes',
            constraint=models.UniqueConstraint(fields=('session_id', 'client_id'), name='unique_vote_per_user'),
        ),
    ]
